# Generated by Django 2.2.1 on 2019-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeaconManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Description of objects associated with this Tag', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='location',
            field=models.CharField(blank=True, help_text="Tag's location", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text="Tag's given name", max_length=100),
        ),
    ]
